### ISSUE TITLE
Migrate issue with no files table

### ISSUE THREAD

**Issue by curtisdelicata** [laravel-enso/HowToVideos#8]
This is  a **bug **.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description
Migrating: 2017_01_01_100000_create_how_to_videos_table

   Illuminate\Database\QueryException

  SQLSTATE[HY000]: General error: 1824 Failed to open the referenced table 'files' (SQL: alter table `how_to_videos` add constraint `how_to_videos_file_id_foreign` foreign key (`file_id`) references `files` (`id`) on delete cascade on update restrict)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:712
    708▕         // If an exception occurs when attempting to run a query, we'll format the error
    709▕         // message to include the bindings with SQL, which will make this exception a
    710▕         // lot more helpful to the developer instead of just the database's errors.
    711▕         catch (Exception $e) {
  ➜ 712▕             throw new QueryException(
    713▕                 $query, $this->prepareBindings($bindings), $e
    714▕             );
    715▕         }
    716▕     }

      +43 vendor frames
  44  artisan:37
      Illuminate\Fo

**Comment by aocneanu** [comment]
Curtis, please wait for v5 release notes / changelog / upgrade steps before diving in core 8.x

**Comment by curtisdelicata** [comment]
Thank you.
